name: wazo-calld-conference
namespace: sboily
version: 0.0.3
author: Sylvain Boily
display_name: Calld extend API Conference
tags:
  - experimental
  - conference
homepage: https://github.com/sboily/wazo-calld-conference
