name: wazo-calld-conference
namespace: sboily
version: 0.0.9
author: Sylvain Boily
display_name: Calld extend API Conference
tags:
  - beta
  - conference
homepage: https://github.com/sboily/wazo-calld-conference
